apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliwebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deliwebapp
  template:
    metadata:
      labels:
        app: deliwebapp
    spec:
    containers:
      - name: deliwebapp
        image: victork01/deliwebapp:latest
        ports:
        - containerPort: 8080
        imagePullSecrets:
      - name: regcred